version: '3.7'
services:
  rust:
    build: .
    volumes:
      - .:/usr/local/src/dlhn
    tty: true
    stdin_open: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: cargo build
